language: python
os:
- linux
python:
- 3.6
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
before_install:
- sudo apt-get update
- sudo apt-get -y install python3-pip python3-setuptools
- sudo pip3 install awscli
install:
- pip install $(cat requirements.txt $(find lib -name requirements.txt | sort) | sort
  | uniq | sed 's/ *== */==/g')
- pip install -r requirements-dev.txt
deploy:
- provider: script
  script: bash ./.travis/build-deploy.sh prod us-east-1
  on:
    branch: TO-779-dockerizing-chief-keeper
notifications:
  email: false
env:
  global:
  - secure: TOAeJczW4PnmCk1ZWgM/iyA/ZMBgar2VG88J4a/yd0NKBnPp2euR/93WmVT9nkGpf+Szj4a5EuOWolwSsRhB0umIae+vSZOzha84AxGChYdY+93lJ7+4nmwYj2XxwS3sjnWoXWk1/BVQopaZbb3xn75j5leSqJ80cdwQiaLrJM3qj/9PKdcfBKpOjBaBWiOyyCvpREADJJkZc07+CdzNyNCWewbPhRJ0A7Svl658nmG7OmxOIiHsCNMyDfpc4qQhMI7TwOHjVt+GiQXFGvviKyy1S84AKGj7ehRjXv/3j4su5YiN3Rd6T0Lq/vUMIfPf24oUlW20MZQWKPegJgtIGTmYcWdjuJhXVXj98bu6jDZ/0Ri/uN4mIxBaP9zPG8xo9Pf4VkwW2leOmXJBlnvGhRsWcw+/bRB03oL+CTjuu4yolxluVbcxLkRAVYElQ+3/EQqeoJauVBBEv6no9XoqftdTCpvO2TZGSaQRtmKXBsqwQBK5R5d7KXDNuYq/wJ8ZOb69cmYWAp3hC3ATMAOwGVaFO+JTQ2FSzoaW7uhHGT4izmC59N+8tAZmxiFhgvliFsN/7IZ67xggj96c6TtvOsJH+W5ZIIvkcocUSwfVBOd+jk6ri2kTNB+L6VMEcBzsYooMtsdQ8hc01TMQs6fl9Y5y+VwF3AX3GgpFmwwNemw=
  - secure: Kgo9Qhc7SVusgfAkeWpDMi8AvSMJ91bghJoL9iUfB65FR88J+t5d/rLkxcNvzoWNGBFuRX7de8R0PkA78jC0iyKpDarQFuqzDjfQaKmfw1nndH9wLoSS4DmA3ozsOxMy0ZS87VGgNt27vbdthskrfNtmYlWbQzLfzQYGBk9+2FKp/THdNs4MeOUT9mCqmsP9r/h3yNwhRJfBMUgkAmdEnDr0NY+9q//jXUsRdsFcdD4Ko3Pj6cZL7qyVMCdJv2YhnpbwDIHNnZQW+UebG+lV87cdxD1VYFMV9KDTPKN+n2WbJWS0r+RTfRsmC4YHL82CMwK43z9vyiwO4GaasyYQfN6k8ODL1bBt18zfLEgpFjjV/ABswUl0YNRu3Om9YuT0BZhykD0KYPDNRzNgTjTTl+qja2QoDfSfMmwb6a+ja0YkQH7eE1DUn9pTs4WcHfbsplR44LFx4SmE478e4RtKV6Pn+0cQgIvyKNx0FYZw5LO4jJVX2W9ekQONbf4Iiq8D4b1IFNz9qEJ3qj3ejdSxxQJd+Ewg/XRtnUheeRF0VCqed8eGXyqPTDzwDitVl/lP675A+uVYtlO67AiH4L/Int2AA9fihoXDRUqjsWKbGO0pwkjZ1VlM72zGkUvV/AOzIDCy2Dlxk2m1JQYeQzHGe9MnWAuiktmOhXCdO9Or0WE=
  - secure: mbsCA07L6tz3fpGIFAoelXIQMNgTXrdwSwcNWZhyH6f2p/oEWaju7LSZE0tqFIr7FWBI2DjGTt/DBDwjKWKMY/HNGv093QzjCtnLZDtN/EQiKqY6TCtWPopmpH8NI9rqF1YY8lnULk+XnkBrszB9/xxcqTNjqgHM93OyNuMCqXcK9/JZuLdNoonfp/duVoFFetFPbI9Pes6wDTzsMyk/kPZ/H0D6k7wtE4XHlwH+TALx8dD+SYS6kRXNlwcp03+mfSGOGttmjvg1zdx8A116YqazdSsYX4VSsz/prin5fr0ngIxG2w2Mem2H7jsPeyZISBr6154odo15IiRgvH4hyE/uSM1+VJ+k85zZe6K8OQWbRHQ0uO7yRQShdUunveS4CVwn+YCxbI248aAl1cRAh20FleloHZT1X6QdXR4QwATS7+mozBFO0hnO6XPP/DmFe4FQfxC8h64R0VVfSFBtyecpdflaGWwTajkCfhgrM0fMtBErp0sjtMdG2wZcCSfjA61lBgGDKqDZ5oktEy490cQcSFdllnhWT9WJruQcYiEDX4jMJqGJ7OI6v18PbsWho2p9mE48jCyV/vmdnpT6pkDtU167OXId4AKyMIUIZgY8gdZIE2PqqY8J7DB9e0a4aE6ELmJ1VazM+C+HJgBPgK+u6uZImOOIqX0F/jTPCPA=
  - secure: EoqWOgsxkNrn2vZLQHjp58lblovmVuTU3/8IaDwN9p5Frwe7p3H7FCynysOIWIvPf4KQXPTSHdmiQTpj5zqY2+me/jSgoDr20dgJZrbAdnp3XQB2x7zgJiY2+/5RJAoLn1ZSyGXo6NKz5DE3/HB3k6DGFBBW40LvdcE86VEBRJlp+2guBF8HTPYpyrgRj4HdBYLX2NyTcU0/9o1sl6PU9WkWSL5ILRAG3UxH/O3cunW2HnZsZVYadyfROyFIRGLWQ3IdtGa7UHrU8+w6MIYAWokqqwl7DimI1gtVfouadvWhrvrRXjlOfRrqIsuA7eD4Xa1qkbZNJ7OzT+CB0gajKEGNQJHp7izDVaxdmyMiRNTsPzhCBERybQTdPQpGyhB36nLogEaVxBQrBbJRzYSUD55wXK+tgcRmOLufsEb0cu2kGD2F10oDITLJI4XkUgHmBbWmtvyFZrr05+N5gvQ0IOVoXHnopRSVa4hpmHEwjiuZeQtjMOQ8t3P6Jo9gCdaiCTNobOtP0xjAqFyB5jLSy+rhMgnP+UkjDuViyCoYZ2YiywhlycO98/B/yFrRCl9fIScG2gf1tqfgUbHwVA9CsghIPJ/L+3KrMoP2oUQllAfolaMCD+FFTqUGqtmaP11ohVfJ8kekQjqfx7WdG4CtI5G9C6fAvOHSXgUzD11yC2E=
